"""initial schema: jobs, evaluations, filter_rules, application_status

Revision ID: eab42bc74d0b
Revises: 
Create Date: 2026-08-17 13:11:11.824961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Bewusst manuell ergänzt: autogenerate rendert unten "pgvector.sqlalchemy.vector.VECTOR(...)"
# als Spaltentyp, vergisst aber den passenden Import — ohne diese Zeile würde
# `alembic upgrade head` mit NameError abbrechen (bekanntes Alembic-Verhalten
# bei Fremd-Typen).
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'eab42bc74d0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector-Extension aktivieren — autogenerate erkennt Extensions
    # nicht, muss deshalb manuell ergänzt werden. IF NOT EXISTS macht
    # den Aufruf idempotent (kein Fehler, wenn die Extension schon da
    # ist, z.B. weil ein anderes Projekt sie auf derselben DB nutzt).
    # Voraussetzung: der Migrations-User muss CREATE-EXTENSION-Recht
    # haben — siehe README-Hinweis für den Fall, dass das nicht gegeben ist.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_blacklist', sa.JSON(), nullable=False),
    sa.Column('max_experience_years', sa.Integer(), nullable=False),
    sa.Column('description_blacklist', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('job_url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('date_posted', sa.String(), nullable=True),
    sa.Column('min_amount', sa.Float(), nullable=True),
    sa.Column('max_amount', sa.Float(), nullable=True),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('found_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=True)
    op.create_table('application_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluations')
    op.drop_table('application_status')
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('filter_rules')
    # ### end Alembic commands ###
